### ISSUE TITLE
После оплаты покупки методом "Pay" на сумму "баланс+кредитный лимит-1" баланс объекта класса "CreditAccount" становится ниже кредитного лимита

### ISSUE THREAD

**Issue by rtmwrk** [rtmwrk/jtm#8]
# Описание
По условиям задания после оплаты покупки баланс кредитного счета должен уменьшиться на сумму покупки, но баланс не может "упасть" ниже кредитного лимита, т.е. ""balance > -creditLimit". Однако, в следствие ошибки в коде метода "Pay" объекта класса "CreditAccount" после оплаты покупки на сумму "balance+creditLimit-1" баланс кредитного счета становится меньше кредитного лимита (-9999), т.е. "balance < -creditLimit". Метод при этом возвращает "true", что означает ошибочное завершение операции, однако баланс все же изменяется. Такое поведение метода нарушает условие задания.

# Локация дефекта
https://github.com/rtmwrk/jtm/blob/94ad854a1d1d796b9c06aa23c7dae36c31a64333/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L41

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/rtmwrk/jtm/blob/credit/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) в IDEA.
2. Создать объект класса "CreditAccount" с параметрами:
- initialBalance = 5000 руб. (начальный баланс кредитного счета);
- creditLimit = 5000 руб. (кредитный лимит);
- rate = 15 % (ставка кредитования при отрицательном балансе счета).
3. Оплатить покупку методом "Pay" на сумму 9999 руб. (account.balance+account.creditLimit-1).

*Ожидаемый результат:* объект класса "CreditAccount" создается, значение баланса кредитного счета "balance" становится равным -4999 руб, метод возвращает "true", что означает успешное завершение операции.

*Фактический результат:* объект класса "CreditAccount" создается, значение баланса кредитного счета "balance" становится равным -9999 руб., при кредитном лимите в 5000 руб., при этом метод возвращает "true", что означает успешное завершение операции. 

# Тест ошибки
https://github.com/rtmwrk/jtm/blob/94ad854a1d1d796b9c06aa23c7dae36c31a64333/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L307

# Скриншот
![issue - balance equal plus creditlimit](https://user-images.githubusercontent.com/125185818/236667676-acc6232d-4745-43b3-9fc3-f9a31eff4adc.jpg)

# Окружение
* **Операционная система:** Windows v. 10 22H2 build 19045.2604
* **IDE:** IntelliJ IDEA 2022.3.2 (Community Edition)
*  **JAVA:** OpenJDK 11

**Comment by Cha1nheart** [comment]
Объект класса "CreditAccount" создается, значение баланса кредитного счета "balance" теперь становится равным -4999 руб., что будет не равно переменной "oldBalance"(создается в тесте). Возможно стоит поменять итоговое сравнение.

**Comment by rtmwrk** [comment]
Учтено, переделано
